credentials:
  usernames:
    mahesh:
      email: mahesh@gmail.com
      name: Mahesh BS
      password: $2b$12$froXPssvPd.BsC5/oHwYs.ZWsXJMZCvUQZyRCB.YWSCtaKjQo9bUq                  # To be replaced with hashed password
    kumar:
      email: kumar@gmail.com
      name: Amith Kumar
      password: def                 # To be replaced with hashed password
    teja:
      email: teja@gmail.com
      name: Teja kumar
      password: teja123
    sravanthi:
      email: sravanthi@gmail.com
      name: sravanthi
      password: $2b$12$arjrtgWsUSrHz9V1mPWTkuUw/ZvDobfAif4lyfSVO0rMwz4EuIz.O

cookie:
  expiry_days: 30
  key: "my_app"                   # Must be string
  name: "login_app"
preauthorized:
  emails:
  - mahesh@gmail.com